import { readFileSync } from "node:fs";
import { execFileSync } from "node:child_process";
import { randomUUID } from "node:crypto";
import { createClient } from "@supabase/supabase-js";
import { expect, test } from "@playwright/test";
import type { Database } from "../../src/lib/supabase/database.types";
import { todayInVilnius } from "../../src/lib/date";

const enabled = process.env.E2E_AUTH_LOCAL === "1" && Boolean(process.env.E2E_AUTH_CREDENTIALS_FILE);
test.skip(!enabled, "Requires disposable local Supabase and ordinary test accounts");
type User = { id: string; email: string; password: string };
type Credentials = { url: string; key: string; a: User; b: User };

test("tracks submission, receipt, response, service, resolution and reopen", async ({ page }) => {
  test.setTimeout(120_000);
  const c = JSON.parse(readFileSync(process.env.E2E_AUTH_CREDENTIALS_FILE!, "utf8")) as Credentials;
  expect(c.url).toMatch(/^http:\/\/127\.0\.0\.1:\d+$/);
  const a = createClient<Database>(c.url, c.key, { auth: { persistSession: false, autoRefreshToken: false } });
  expect((await a.auth.signInWithPassword(c.a)).error).toBeNull();
  const purchaseId = randomUUID(), complaintId = randomUUID(), versionId = randomUUID();
  const today = todayInVilnius();
  const purchase = await a.from("purchases").insert({ id: purchaseId, user_id: c.a.id, product_name: "Bandomasis dviratis", seller_name: "Bandymų parduotuvė", purchase_date: today, purchase_channel: "PHYSICAL_STORE" }).select("*").single();
  expect(purchase.error).toBeNull();
  try {
    expect((await a.from("complaints").insert({ id: complaintId, user_id: c.a.id, purchase_id: purchaseId, family: "DEFECTIVE_PRODUCT", request_id: randomUUID(), answers: {}, facts: {}, remedy: "REPAIR", purchase_updated_at: purchase.data!.updated_at, template_version: "test", source_version: "test" })).error).toBeNull();
    const sql = `insert into public.complaint_versions(id,user_id,purchase_id,complaint_id,version_no,request_id,document_date,snapshot,sections,plain_text,template_version,source_version) values ('${versionId}','${c.a.id}','${purchaseId}','${complaintId}',1,'${randomUUID()}','${today}','{}','[]','Synthetic document','test','test')`;
    execFileSync("docker", ["exec", "supabase_db_pirkejo-skydas", "psql", "-U", "postgres", "-d", "postgres", "-v", "ON_ERROR_STOP=1", "-c", sql], { stdio: "ignore" });
    await page.goto("/login");
    const login = page.getByRole("heading", { name: "Prisijungti" }).locator("..");
    await login.getByLabel("El. paštas").fill(c.a.email);
    await login.getByLabel("Slaptažodis").fill(c.a.password);
    await login.getByRole("button", { name: "Prisijungti" }).click();
    await expect(page).toHaveURL(/\/purchases/);
    await page.goto(`/purchases/${purchaseId}/complaints/${complaintId}`);
    await page.getByRole("button", { name: "Sekti kreipimąsi" }).click();
    await expect(page).toHaveURL(/\/cases\/[0-9a-f-]{36}$/);
    const caseId = page.url().split("/").pop()!;
    expect((await a.from("cases").select("complaint_version_id").eq("id", caseId).single()).data?.complaint_version_id).toBe(versionId);
    await expect(page.getByText("Dokumentas parengtas", { exact: true })).toBeVisible();
    await expect(page.getByText("Dokumentas dar nepateiktas pardavėjui.")).toBeVisible();
    const form = page.getByRole("heading", { name: "Įrašyti įvykį" }).locator("..").locator("form");
    await form.getByLabel("Data", { exact: true }).fill(today);
    await form.getByRole("button", { name: "Išsaugoti įrašą" }).click();
    await expect(page.getByText("Pardavėjo gavimo data nežinoma", { exact: true })).toBeVisible();
    await form.getByLabel("Veiksmas").selectOption("RECEIPT_RECORDED");
    await form.locator('input[name="occurredOn"]').fill(today);
    await form.getByRole("button", { name: "Išsaugoti įrašą" }).click();
    await expect(page.getByText("Atsakymo termino pabaiga:", { exact: false })).toBeVisible();
    await form.getByLabel("Veiksmas").selectOption("RESPONSE_RECORDED");
    await form.getByLabel("Mano atsakymo aprašymas").fill("Pardavėjas prašo papildomų nuotraukų.");
    await form.getByLabel("Mano nurodytas atsakymo pobūdis").selectOption("MORE_INFORMATION");
    await form.getByRole("button", { name: "Išsaugoti įrašą" }).click();
    await expect(page.getByText("Pardavėjas prašo papildomų nuotraukų.")).toBeVisible();
    await form.getByLabel("Veiksmas").selectOption("SERVICE_STARTED");
    await form.getByRole("button", { name: "Išsaugoti įrašą" }).click();
    await expect(page.getByText("Prekė taisoma / tikrinama", { exact: true })).toBeVisible();
    await form.getByLabel("Veiksmas").selectOption("SERVICE_RETURNED");
    await form.getByLabel("Trumpas rezultatas").fill("Prekė atgauta.");
    await form.getByRole("button", { name: "Išsaugoti įrašą" }).click();
    await expect(page.getByText("Prekė atgauta", { exact: false })).toBeVisible();
    await expect(page.getByText("Gautas pardavėjo atsakymas", { exact: true })).toBeVisible();
    await form.getByLabel("Veiksmas").selectOption("RESOLVED");
    await form.getByLabel("Pasiektas rezultatas").selectOption("REPAIRED");
    await form.getByRole("button", { name: "Išsaugoti įrašą" }).click();
    await expect(page.getByText("Išspręsta", { exact: true })).toBeVisible();
    await expect(form.getByLabel("Veiksmas")).toHaveValue("REOPENED");
    page.once("dialog", (dialog) => dialog.accept());
    await form.getByRole("button", { name: "Išsaugoti įrašą" }).click();
    await expect(page.getByText("Gautas pardavėjo atsakymas", { exact: true })).toBeVisible();
    await form.getByLabel("Trumpa pastaba (nebūtina)").fill("Neišsaugota pastaba");
    page.once("dialog", (dialog) => dialog.dismiss());
    await page.getByRole("link", { name: "← Mano kreipimaisi" }).click();
    await expect(page).toHaveURL(new RegExp(`/cases/${caseId}$`));
    await expect(form.getByLabel("Trumpa pastaba (nebūtina)")).toHaveValue("Neišsaugota pastaba");
    page.once("dialog", (dialog) => dialog.accept());
    await page.getByRole("link", { name: "← Mano kreipimaisi" }).click();
    await expect(page).toHaveURL(/\/cases$/);
    await page.goto(`/cases/${caseId}`);
    await page.setViewportSize({ width: 390, height: 844 });
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
    await page.reload();
    await expect(page.getByText("Bandomasis dviratis", { exact: true })).toBeVisible();
  } finally {
    await a.from("purchases").update({ deletion_state: "DELETING" }).eq("id", purchaseId);
    await a.from("purchases").delete().eq("id", purchaseId);
    await a.auth.signOut();
  }
});
