import Link from "next/link";
import { ArrowRight, CheckCircle2, FileQuestion, PackageCheck, ReceiptText, ShieldCheck, Store } from "lucide-react";
import { Button } from "@/components/ui/button";

const upcoming = [
  { title: "Nerandu čekio", icon: ReceiptText },
  { title: "Prekė per ilgai servise", icon: Store },
  { title: "Pardavėjas nepadeda", icon: FileQuestion }
];

export default function Home() {
  return <main className="min-h-screen"><div className="mx-auto max-w-6xl px-5 pb-20 pt-6 sm:px-8"><header className="flex items-center justify-between border-b border-slate-200 pb-6"><div className="flex items-center gap-3 text-teal-950"><div className="rounded-xl bg-teal-900 p-2 text-white"><ShieldCheck size={21} /></div><span className="text-lg font-bold tracking-tight">Pirkėjo Skydas</span></div><span className="hidden text-xs font-semibold uppercase tracking-[0.18em] text-slate-400 sm:block">Aiškiau apie jūsų teises</span></header>
    <section className="grid gap-10 pb-12 pt-16 md:grid-cols-[1.25fr_0.75fr] md:items-center md:gap-16 md:py-24"><div><div className="mb-7 inline-flex items-center gap-2 rounded-full border border-teal-200 bg-teal-50 px-3 py-2 text-xs font-bold uppercase tracking-[0.12em] text-teal-800"><CheckCircle2 size={16} /> Paprasti atsakymai pirkėjams</div><h1 className="max-w-2xl text-5xl font-bold leading-[1.08] tracking-tight text-slate-950 sm:text-6xl">Pirkėjo<br /><span className="text-teal-800">Skydas</span></h1><p className="mt-6 max-w-lg text-xl leading-8 text-slate-600">Žinok savo teises po kiekvieno pirkimo.</p><p className="mt-5 max-w-lg text-sm leading-7 text-slate-500">Atsakykite į kelis paprastus klausimus ir sužinokite, kokie grąžinimo žingsniai gali tikti jūsų situacijai.</p><Button asChild className="mt-9 w-full sm:w-auto"><Link href="/returns">Ar galiu grąžinti prekę? <ArrowRight size={18} /></Link></Button></div><div className="rounded-[2rem] border border-teal-200 bg-teal-900 p-8 text-white shadow-xl shadow-teal-950/10 sm:p-10"><div className="mb-10 flex h-14 w-14 items-center justify-center rounded-2xl bg-white/10"><PackageCheck size={29} /></div><p className="text-xs font-bold uppercase tracking-[0.2em] text-teal-200">Pirmasis žingsnis</p><h2 className="mt-4 text-3xl font-bold leading-tight">Grąžinimas be spėliojimo.</h2><p className="mt-5 text-sm leading-7 text-teal-100">Skirtingiems pirkiniams taikomos skirtingos taisyklės. Pateiksime aiškų atsakymą pagal jūsų pasirinkimus ir nuorodas į oficialius šaltinius.</p><div className="mt-10 border-t border-white/20 pt-5 text-sm text-teal-100">Paprasta. Aišku. Jūsų tempu.</div></div></section>
    <section className="border-t border-slate-200 pt-10"><div className="mb-6 flex items-end justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-teal-800">Kitos situacijos</p><h2 className="mt-2 text-2xl font-bold tracking-tight text-slate-950">Pasirinkite situaciją</h2></div></div><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Link href="/defective-product" className="flex min-h-32 flex-col items-start justify-between rounded-2xl border border-teal-200 bg-white p-5 text-left transition hover:border-teal-600 hover:bg-teal-50 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-teal-600"><PackageCheck size={24} className="text-teal-800" /><span className="flex w-full items-end justify-between gap-3"><span className="text-sm font-semibold text-slate-900">Prekė sugedo</span><ArrowRight size={17} className="text-teal-700" /></span></Link>{upcoming.map(({ title, icon: Icon }) => <button key={title} disabled className="flex min-h-32 flex-col items-start justify-between rounded-2xl border border-slate-200 bg-white p-5 text-left opacity-60"><Icon size={24} className="text-slate-500" /><span className="flex w-full items-end justify-between gap-3"><span className="text-sm font-semibold text-slate-800">{title}</span><span className="text-[10px] font-bold uppercase tracking-wider text-slate-500">Netrukus</span></span></button>)}</div></section></div></main>;
}
