import type { DefectiveProductDecisionCode } from "../domain/types";

export const resultCopy: Record<DefectiveProductDecisionCode, { title: string; summary: string }> = {
  NEEDS_MORE_INFORMATION: { title: "Reikia daugiau informacijos", summary: "Pagal pateiktus atsakymus dar negalima patikimai parinkti kito žingsnio." },
  NOT_CONSUMER_PURCHASE: { title: "Ši situacija nepatenka į įprastą vartotojų teisių apsaugą", summary: "Pirkėjo Skydas šiuo metu skirtas fizinių asmenų pirkiniams, įsigytiems asmeniniams, o ne verslo poreikiams." },
  PRIVATE_SELLER: { title: "Šiam pirkimui gali būti taikomos kitos taisyklės", summary: "Ši patikra skirta pirkiniams iš verslininkų. Pirkimams iš privataus asmens įprastos vartotojų apsaugos taisyklės taikomos kitaip." },
  SELLER_STATUS_REVIEW_REQUIRED: { title: "Pirmiausia išsiaiškinkite, kas buvo pardavėjas", summary: "Jei pardavėjo statusas neaiškus, negalime pritaikyti vartotojo ir verslininko sandorių taisyklių." },
  UNSUPPORTED_TRANSACTION_TYPE: { title: "Ši patikra skirta fizinėms prekėms", summary: "Skaitmeniniam turiniui ir paslaugoms gali būti taikomos kitokios taisyklės." },
  USED_GOODS_TERM_REVIEW_REQUIRED: { title: "Reikia patikrinti naudotos prekės sutartą terminą", summary: "Naudotai prekei dvejų metų laikotarpis netrumpėja automatiškai. Trumpesnis terminas turi būti sutartas ir negali būti trumpesnis nei vieni metai." },
  INVALID_DATE: { title: "Patikrinkite įvestas datas", summary: "Viena iš datų negalioja arba įvykių tvarka neįmanoma. Patikslinkite datas ir bandykite dar kartą." },
  STATUTORY_LIABILITY_PERIOD_APPEARS_EXPIRED: { title: "Įprastas garantijos pagal įstatymą laikotarpis, panašu, jau pasibaigė", summary: "Tai savaime nereiškia, kad nebeturite galimybių. Gali būti aktuali ilgesnė komercinė garantija arba tam tikroms prekėms taikoma teisė į taisymą." },
  CAUSE_REVIEW_REQUIRED: { title: "Trūkumo priežastį reikia įvertinti atidžiau", summary: "Garantija pagal įstatymą paprastai taikoma už trūkumą, už kurį atsako pardavėjas. Po smūgio ar kito įvykio atsiradusiai žalai gali reikėti kitokio vertinimo." },
  PURCHASE_EVIDENCE_MISSING: { title: "Pabandykite rasti pirkimo įrodymą", summary: "Įrodymas, kad pirkote iš šio pardavėjo, yra svarbus. Popierinis čekis nėra vienintelis galimas įrodymas, o jo neturėjimas savaime nereiškia, kad teisių nėra." },
  CONTACT_SELLER_REPAIR_OR_REPLACE: { title: "Pirmas žingsnis – raštu kreiptis į pardavėją", summary: "Pirmiausia dėl nekokybiškos prekės paprastai galite pasirinkti remontą arba pakeitimą, jeigu pasirinktas būdas nėra neįmanomas ar neproporcingas." },
  PRIMARY_REMEDY_FIRST: { title: "Pinigų grąžinimas ne visada yra pirmas žingsnis", summary: "Pagal pateiktą informaciją pirmiausia gali būti taikomas remontas arba pakeitimas. Kainos sumažinimas ar sutarties nutraukimas galimas esant įstatyme numatytoms aplinkybėms." },
  CLAIM_REQUIREMENT_UNCLEAR: { title: "Rašytinėje pretenzijoje aiškiai nurodykite reikalavimą", summary: "VVTAT rekomenduoja nurodyti, kokio sprendimo prašote. Neaiškus reikalavimas savaime nereiškia, kad kreipimasis negalioja." },
  SELLER_RESPONSE_PERIOD_RUNNING: { title: "Pardavėjo atsakymo terminas dar nepasibaigė", summary: "Pardavėjas į rašytinę pretenziją paprastai turi atsakyti ne vėliau kaip per 14 kalendorinių dienų nuo jos gavimo." },
  SELLER_RESPONSE_OVERDUE: { title: "Pardavėjo atsakymo terminas, panašu, jau pasibaigė", summary: "Jei pardavėjas laiku neatsakė į rašytinę pretenziją, gali būti pagrindas kreiptis į VVTAT dėl ginčo nagrinėjimo ne teismo tvarka." },
  SELLER_REFUSAL_REVIEW_REQUIRED: { title: "Pardavėjo atsisakymą reikia įvertinti", summary: "Atsisakymas savaime neįrodo pažeidimo. Svarbu, ko prašėte, ką pardavėjas atsakė ir ar buvo pagrindas pereiti prie kainos mažinimo ar sutarties nutraukimo." },
  SECONDARY_REMEDIES_MAY_BE_AVAILABLE: { title: "Kainos sumažinimas ar sutarties nutraukimas gali būti galimas", summary: "Pagal pateiktą informaciją gali būti pagrindas svarstyti kitą sprendimą, jei pardavėjas atsisakė taisyti ar keisti prekę arba trūkumas liko po bandymo jį pašalinti." },
  SERIOUSNESS_REVIEW_REQUIRED: { title: "Trūkumo reikšmingumą reikia įvertinti", summary: "Vien vartotojo apibūdinimo nepakanka nuspręsti, ar trūkumas teisiškai esminis arba nedidelis." },
  REPAIR_DELAY_REVIEW_REQUIRED: { title: "Stebėkite remonto ar pakeitimo eigą", summary: "Remontas ar pakeitimas turi būti atliktas nemokamai, per protingą terminą ir nesukeliant didelių nepatogumų. Vieno visoms prekėms taikomo remonto dienų skaičiaus nėra." },
  VVTAT_ESCALATION_MAY_BE_AVAILABLE: { title: "Kitas žingsnis gali būti VVTAT", summary: "Jei raštu kreipėtės į pardavėją ir jo pasiūlymas netenkina jūsų reikalavimo, galite svarstyti ginčo nagrinėjimą VVTAT / VTIS." },
  COMMERCIAL_GUARANTEE_MAY_APPLY: { title: "Gali būti taikoma komercinė garantija", summary: "Ilgesnė pardavėjo ar gamintojo suteikta garantija gali suteikti papildomų galimybių pagal jos sąlygas. Ji nepanaikina garantijos pagal įstatymą." },
  POST_GUARANTEE_REPAIR_RIGHT_MAY_APPLY: { title: "Šiai prekių kategorijai gali būti taikoma teisė į taisymą", summary: "Gamintojo pareiga taisyti tam tikrų grupių prekes skiriasi nuo nemokamos pardavėjo atsakomybės pagal įstatyminę garantiją. Už tokį remontą gali būti imamas pagrįstas mokestis." },
  RIGHT_TO_REPAIR_REVIEW_REQUIRED: { title: "Teisės į taisymą taikymą reikia patikrinti", summary: "Gamintojo taisymo pareiga priklauso nuo konkrečios prekės ir jai taikomų taisomumo reikalavimų. Vien iš šių atsakymų to nustatyti negalima." },
  SELLER_OFFER_ACCEPTED: { title: "Suderinkite pasiūlyto sprendimo sąlygas", summary: "Jei kitas pardavėjo pasiūlymas jus tenkina, susitarkite raštu, kada ir kaip jis bus įvykdytas." },
  CASE_RESOLVED: { title: "Panašu, kad problema išspręsta", summary: "Išsaugokite pardavėjo atsakymą ir remonto arba pakeitimo dokumentus, jei jų turite." }
};
export const stepCopy: Record<string, string> = {
  AGREE_OFFER_DETAILS: "Raštu patvirtinkite sutartą sprendimą ir jo įvykdymo laiką.",
  CHECK_FACTS: "Patikslinkite trūkstamus faktus arba pasitarkite su VVTAT.", SEEK_OTHER_ADVICE: "Ieškokite konsultacijos dėl verslo pirkimo sutarties.", CHECK_CONTRACT: "Peržiūrėkite susitarimą su privačiu pardavėju.", IDENTIFY_SELLER: "Patikrinkite sąskaitą, užsakymo informaciją ir pardavėjo rekvizitus.", CHECK_OTHER_RULES: "Pasidomėkite taisyklėmis, taikomomis jūsų paslaugai ar skaitmeniniam turiniui.", CHECK_USED_AGREEMENT: "Patikrinkite, ar dėl trumpesnio termino buvo aiškiai susitarta perkant.", CHECK_DATES: "Patikrinkite prekės gavimo ir kitų įvykių datas.", CHECK_COMMERCIAL_OR_REPAIR: "Patikrinkite komercinės garantijos sąlygas ir prekės taisomumo kategoriją.", PRESERVE_CAUSE_EVIDENCE: "Išsaugokite trūkumo nuotraukas, aprašymą ir aplinkybių įrodymus.", FIND_PURCHASE_EVIDENCE: "Ieškokite sąskaitos, banko išrašo, užsakymo patvirtinimo ar kito pirkimo įrodymo.", DESCRIBE_DEFECT: "Aprašykite, kada ir kaip pasireiškė trūkumas.", REQUEST_PRIMARY_REMEDY: "Aiškiai pasirinkite remontą arba pakeitimą, atsižvelgdami į konkrečią situaciją.", SEND_WRITTEN_CLAIM: "Raštu kreipkitės į pardavėją ir pridėkite turimą pirkimo įrodymą.", SAVE_CLAIM: "Išsaugokite pretenzijos kopiją ir įrodymą, kada pardavėjas ją gavo.", CLARIFY_DEMAND: "Raštu patikslinkite pardavėjui, kokio sprendimo prašote.", WAIT_FOR_RESPONSE: "Sulaukite atsakymo arba pasitikrinkite, ar terminas jau pasibaigė.", CONSIDER_VVTAT: "Jei ginčas neišspręstas, peržiūrėkite VVTAT kreipimosi tvarką.", REVIEW_REFUSAL: "Peržiūrėkite pardavėjo nurodytas atsisakymo priežastis.", CONSIDER_SECONDARY: "Įvertinkite proporcingą kainos sumažinimą arba sutarties nutraukimą pagal konkrečias aplinkybes.", SAVE_REPAIR_RECORDS: "Išsaugokite serviso ir ankstesnio remonto dokumentus.", GET_ASSESSMENT: "Prireikus kreipkitės dėl nepriklausomo trūkumo įvertinimo.", ASK_REPAIR_TIMELINE: "Raštu pasiteiraukite pardavėjo apie numatomą remonto ar pakeitimo eigą.", CHECK_COMMERCIAL_TERMS: "Peržiūrėkite komercinės garantijos dokumentą ir jo galiojimo sąlygas.", CHECK_MANUFACTURER_REPAIR: "Patikrinkite gamintojo skelbiamą taisymo informaciją ir konkrečios prekės taisomumo taisykles.", CHECK_PRODUCT_RULES: "Patikrinkite tikslų modelį ir jam taikomų taisomumo taisyklių laikotarpį.", SAVE_RESOLUTION: "Išsaugokite sprendimo ir prekės perdavimo dokumentus."
};
export const warningCopy: Record<string, string> = {
  LATER_PROOF: "Jei trūkumas paaiškėjo po pirmųjų metų, jo kilmės įrodymai gali tapti svarbesni. Tai savaime nepanaikina teisių.", TIMING_UNKNOWN: "Nežinant, kada pirmą kartą pasireiškė trūkumas, laikotarpio ir įrodinėjimo vertinimas gali būti netikslus.", PURCHASE_DATE_UNKNOWN: "Nežinant pirkimo datos negalima patikimai nustatyti, ar taikomas papildomų metų pratęsimas pasirinkus remontą.", VERBAL_NOT_WRITTEN: "Vien žodinis pokalbis paprastai nepakanka VVTAT ginčo procedūrai: pirmiausia raštu nurodykite reikalavimą pardavėjui.", RECEIPT_DATE_UNKNOWN: "Nežinant, kada pardavėjas gavo pretenziją, negalima patikimai apskaičiuoti 14 dienų termino.", REFUND_NOT_AUTOMATIC: "Vien atsisakymas iš karto grąžinti pinigus nereiškia, kad pardavėjas pažeidė taisykles."
};
export const infoCopy: Record<string, { title: string; text: string }> = {
  FIRST_YEAR_PRESUMPTION: { title: "Pirmųjų metų trūkumas", text: "Per pirmuosius metus paaiškėjęs trūkumas paprastai laikomas buvusiu prekės perdavimo metu, nebent įrodoma kitaip arba tai nesuderinama su prekės ar trūkumo pobūdžiu. Tai negarantuoja ginčo baigties." },
  REPAIR_EXTENSION: { title: "Pasirinkus remontą gali būti pratęsta garantija pagal įstatymą", text: "Pagal nuo 2026 m. liepos 31 d. taikomas taisykles, atitinkamais atvejais pasirinkus remontą vietoj pakeitimo, pardavėjo atsakomybės laikotarpis pratęsiamas papildomiems metams. Tai nėra gamintojo komercinė garantija." },
  RESPONSE_NOT_REPAIR_DEADLINE: { title: "14 dienų yra atsakymo terminas", text: "Šis terminas skirtas atsakyti į rašytinę pretenziją. Jis nėra visiems remontams taikomas užbaigimo terminas." },
  REPAIR_REASONABLE_TIME: { title: "Remontas ir pakeitimas", text: "Pardavėjo atsakomybės laikotarpiu jie paprastai turi būti nemokami, atlikti per protingą terminą ir nesukelti didelių nepatogumų." },
  MINOR_DEFECT_LIMIT: { title: "Sutarties nutraukimo riba", text: "Sutarties negalima nutraukti dėl tik nedidelio trūkumo. Kad trūkumas nedidelis, turi įrodyti pardavėjas; šioje patikroje galutinio vertinimo nedarome." },
  VVTAT: { title: "Kitas žingsnis gali būti VVTAT", text: "Jei pardavėjas atmetė ar tik iš dalies patenkino rašytinį reikalavimą arba laiku neatsakė, galite svarstyti kreipimąsi į VVTAT per VTIS. Išsaugokite pretenziją ir atsakymą." }
};
export const evidenceCopy: Record<string, string> = {
  PURCHASE: "Pirkimo dokumentą ar kitą pirkimo įrodymą", DEFECT: "Prekės nuotraukas, vaizdo įrašus ir trūkumo aprašymą", CORRESPONDENCE: "Susirašinėjimą su pardavėju ir pretenzijos gavimo įrodymą", REPAIR_RECORDS: "Serviso, diagnostikos ir ankstesnio remonto dokumentus", SELLER_RESPONSE: "Pardavėjo rašytinį atsakymą"
};
